### ISSUE TITLE
Just saying hello!

### ISSUE THREAD

**Issue by mdroidian** [jmilldotdev/obsidian-idea-clock#2]
Just found this plugin from the Obsidian Roundup.  

I've been very interested in a canvas app.  
I've been trying to collect my ideas around Canvas / Whiteboard / Spatial-Visual representation and integration in PKM.  And testing a few programs.

Here's a similar plugin obsidian thread, if you haven't seen it yet.
https://forum.obsidian.md/t/concept-map-plugin-idea/21256

Excited to see how this pans out!

**Comment by jmilldotdev** [comment]
Hey, thanks! Glad you're using it.
