### ISSUE TITLE
[BUG]Websocket error messages

### ISSUE THREAD

**Issue by Quorafind** [jmilldotdev/obsidian-idea-clock#3]
![image](https://user-images.githubusercontent.com/13215013/141718963-73c959d1-1438-4899-bdf8-4057dce3a6af.png)

I tried to reopen all plugins to find which plugin output these messages, and I found they were from your plugin.

**Comment by jmilldotdev** [comment]
Oops, I left in React Devtools 😳

Should be fixed in new release
